### ISSUE TITLE
Crealla-Prolog crashes

### ISSUE THREAD

**Issue by mlliarm** [mlliarm/ia#23]
Error msg:

```
Run logtalk_tester -p trealla-prolog -f xunit -c xml || EXIT=$?
Error! Unsupported backend Prolog compiler: trealla-prolog

This script automates running unit tests found in the current directory and
recursively in its sub-directories by scanning by default for "tester.lgt"
and "tester.logtalk" source files. In case of failed unit tests or test set
errors, this script returns a non-zero exit code. When a "tester.sh" file
exists in the tests directory, the file is sourced before running the tests.
The "tester.sh" file is sourced with all the parameters passed to the script.
The timeout option requires availability of the GNU coreutils timeout command.
```
from [here](https://github.com/mlliarm/ia/runs/4878461274?check_suite_focus=true#step:12:1), 

and

```
TypeError: Cannot write private member to an object whose class did not declare it
    at O (/usr/local/lib/node_modules/xunit-viewer/node_modules/yargs/build/index.cjs:1:3360)
    at showHelp (/usr/local/lib/node_modules/xunit-viewer/node_modules/yargs/build/index.cjs:1:40491)
    at module.exports (/usr/local/lib/node_modules/xunit-viewer/xunit-viewer.js:19:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/xunit-viewer/bin/xunit-viewer:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
Error: Process completed with exit code 1.
```

from [here](https://github.com/mlliarm/ia/runs/4878461274?check_suite_focus=true#step:12:59).

**Comment by pmoura** [comment]
```text
Error! Unsupported backend Prolog compiler: trealla-prolog
```

Either `logtalk_tester -h` or `man logtalk_tester` will tell you the **valid Prolog identifiers** to use.
